name: phum_delivery
description: "Phum Delivery"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.5.1
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_crashlytics: ^5.0.2
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.17
  flutter_flavorizr: ^2.4.1
  http: ^1.5.0
  hexcolor: ^3.0.1
  pinput: ^5.0.2
  flutter_spinkit: ^5.2.2
  cached_network_image: ^3.4.1
  fluttertoast: ^9.0.0
  collection: ^1.19.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_sticky_header: ^0.8.0
  flutter_localizations:
    sdk: flutter
  get_storage: ^2.1.1
  dotted_line: ^3.2.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0     

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/svg/
    - assets/images/
    - assets/gif/
    - assets/svg/setting/
    

flavorizr:
  ide: "vscode"
  flavors:
    dev:
      app:
        name: "Delivery Dev"
      android:
        applicationId: "com.phum.delivery.dev"
        firebase:
          config: ".firebase/dev/android/google-services.json"
      ios:
        bundleId: "com.phum.delivery.dev"
        firebase:
          config: ".firebase/dev/ios/GoogleService-Info.plist"
         

    staging:
      app:
        name: "Delivery Staging"
      android:
        applicationId: "com.phum.delivery.staging"
        firebase:
          config: ".firebase/staging/android/google-services.json"
      ios:
        bundleId: "com.phum.delivery.staging"
        firebase:
          config: ".firebase/staging/ios/GoogleService-Info.plist"
        
    prod:
      app:
        name: "Delivery Prod"
      android:
        applicationId: "com.phum.delivery"
        firebase:
          config: ".firebase/prod/android/google-services.json"
      ios:
        bundleId: "com.phum.delivery"
        firebase:
          config: ".firebase/prod/ios/GoogleService-Info.plist"
