// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvJqLXEaOBBLpHUJFjCFtm4ZM9JlgYVtM',
    appId: '1:187044582223:web:c858862a720987f4f92b3a',
    messagingSenderId: '187044582223',
    projectId: 'mvvm-solid-principle-dev',
    authDomain: 'mvvm-solid-principle-dev.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle-dev.firebasestorage.app',
    measurementId: 'G-GBP7FYXRE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5NLEuJdsiJu43G81mshISEHOhyMmMXQ',
    appId: '1:187044582223:android:9f1927b13fa3bd6ff92b3a',
    messagingSenderId: '187044582223',
    projectId: 'mvvm-solid-principle-dev',
    storageBucket: 'mvvm-solid-principle-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH5IvazWsX7bJ6w_FgiBj2ry5geMeNAQU',
    appId: '1:187044582223:ios:473367ffde45e5e9f92b3a',
    messagingSenderId: '187044582223',
    projectId: 'mvvm-solid-principle-dev',
    storageBucket: 'mvvm-solid-principle-dev.firebasestorage.app',
    iosBundleId: 'com.solid.principle.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH5IvazWsX7bJ6w_FgiBj2ry5geMeNAQU',
    appId: '1:187044582223:ios:f148fa7d64c290e3f92b3a',
    messagingSenderId: '187044582223',
    projectId: 'mvvm-solid-principle-dev',
    storageBucket: 'mvvm-solid-principle-dev.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvJqLXEaOBBLpHUJFjCFtm4ZM9JlgYVtM',
    appId: '1:187044582223:web:555d1ea0031d1ccdf92b3a',
    messagingSenderId: '187044582223',
    projectId: 'mvvm-solid-principle-dev',
    authDomain: 'mvvm-solid-principle-dev.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle-dev.firebasestorage.app',
    measurementId: 'G-PRSTJJ028K',
  );
}
