// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6hNVUM7gcTuqUBkqQHA6QLWCmFocdOo',
    appId: '1:444884163011:web:2c2b6ee35e16aeec68c576',
    messagingSenderId: '444884163011',
    projectId: 'penh-delivery',
    authDomain: 'penh-delivery.firebaseapp.com',
    storageBucket: 'penh-delivery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd0DPSH10qexZQKmmcHzPuivgK_jSTuKI',
    appId: '1:444884163011:android:255b5f7f136ac42068c576',
    messagingSenderId: '444884163011',
    projectId: 'penh-delivery',
    storageBucket: 'penh-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzaizHoWfu4ayagRgkm6Nzr8acVBr7p3w',
    appId: '1:444884163011:ios:c337525cf24e7f6e68c576',
    messagingSenderId: '444884163011',
    projectId: 'penh-delivery',
    storageBucket: 'penh-delivery.firebasestorage.app',
    iosBundleId: 'com.penh.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzaizHoWfu4ayagRgkm6Nzr8acVBr7p3w',
    appId: '1:444884163011:ios:a8990876ff02e67168c576',
    messagingSenderId: '444884163011',
    projectId: 'penh-delivery',
    storageBucket: 'penh-delivery.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_6hNVUM7gcTuqUBkqQHA6QLWCmFocdOo',
    appId: '1:444884163011:web:05b31deef9160ef968c576',
    messagingSenderId: '444884163011',
    projectId: 'penh-delivery',
    authDomain: 'penh-delivery.firebaseapp.com',
    storageBucket: 'penh-delivery.firebasestorage.app',
  );

}