// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7qYsycK7cPf7WGAP4PrKYD8WfimxjA8g',
    appId: '1:677667737775:android:0eacb853ac4e7c2152445a',
    messagingSenderId: '677667737775',
    projectId: 'phum-delivery-26b4c',
    storageBucket: 'phum-delivery-26b4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVZs9oe7_cUIoITn2rgfOb16iGs5vo5TQ',
    appId: '1:677667737775:ios:e0ca9c9c93391c3552445a',
    messagingSenderId: '677667737775',
    projectId: 'phum-delivery-26b4c',
    storageBucket: 'phum-delivery-26b4c.firebasestorage.app',
    androidClientId: '677667737775-225appjhaq5h8sp2sa5hfgln20ch1m3d.apps.googleusercontent.com',
    iosClientId: '677667737775-apthglr5for9fuo3etvfis1e68qvifq9.apps.googleusercontent.com',
    iosBundleId: 'com.phum.delivery',
  );

}