// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGGNE4CDGus9rl81E4YvaCYqV0fFsBos',
    appId: '1:589539129257:web:bd17852fc605e201fb76b8',
    messagingSenderId: '589539129257',
    projectId: 'penh-delivery-dev',
    authDomain: 'penh-delivery-dev.firebaseapp.com',
    storageBucket: 'penh-delivery-dev.firebasestorage.app',
    measurementId: 'G-WTFZ8ZCT65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh9mK6MctKOP5ysbkB6jAsdskk4geOpLE',
    appId: '1:589539129257:android:8806dd234a13ba31fb76b8',
    messagingSenderId: '589539129257',
    projectId: 'penh-delivery-dev',
    storageBucket: 'penh-delivery-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFwiRRR8SCGKOLLoA-CqpjQVnznfOwO3I',
    appId: '1:589539129257:ios:d9731034cb7ea52afb76b8',
    messagingSenderId: '589539129257',
    projectId: 'penh-delivery-dev',
    storageBucket: 'penh-delivery-dev.firebasestorage.app',
    iosBundleId: 'com.penh.delivery.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFwiRRR8SCGKOLLoA-CqpjQVnznfOwO3I',
    appId: '1:589539129257:ios:8528106933e9fb89fb76b8',
    messagingSenderId: '589539129257',
    projectId: 'penh-delivery-dev',
    storageBucket: 'penh-delivery-dev.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApGGNE4CDGus9rl81E4YvaCYqV0fFsBos',
    appId: '1:589539129257:web:f98f75bdf1f25155fb76b8',
    messagingSenderId: '589539129257',
    projectId: 'penh-delivery-dev',
    authDomain: 'penh-delivery-dev.firebaseapp.com',
    storageBucket: 'penh-delivery-dev.firebasestorage.app',
    measurementId: 'G-EFTMDFPC4Q',
  );

}