// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPL7O23fDf6A3JkrZ2LsPTH9U40mQeylA',
    appId: '1:894248668835:web:ea6f871490f729a11e7916',
    messagingSenderId: '894248668835',
    projectId: 'mvvm-solid-principle-staging',
    authDomain: 'mvvm-solid-principle-staging.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle-staging.firebasestorage.app',
    measurementId: 'G-NYKPDPLXB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs5b9jFg8F1dvtNkEmbcvqjZY9Lmu2ulc',
    appId: '1:894248668835:android:e9742da01a3b60711e7916',
    messagingSenderId: '894248668835',
    projectId: 'mvvm-solid-principle-staging',
    storageBucket: 'mvvm-solid-principle-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQIvTFyrXLGXH_VdqKOxsAbxj56s83Z4',
    appId: '1:894248668835:ios:b21fdc194c39d6dc1e7916',
    messagingSenderId: '894248668835',
    projectId: 'mvvm-solid-principle-staging',
    storageBucket: 'mvvm-solid-principle-staging.firebasestorage.app',
    iosBundleId: 'com.solid.principle.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQIvTFyrXLGXH_VdqKOxsAbxj56s83Z4',
    appId: '1:894248668835:ios:64622205d2057f681e7916',
    messagingSenderId: '894248668835',
    projectId: 'mvvm-solid-principle-staging',
    storageBucket: 'mvvm-solid-principle-staging.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPL7O23fDf6A3JkrZ2LsPTH9U40mQeylA',
    appId: '1:894248668835:web:10f92e523a755e0e1e7916',
    messagingSenderId: '894248668835',
    projectId: 'mvvm-solid-principle-staging',
    authDomain: 'mvvm-solid-principle-staging.firebaseapp.com',
    storageBucket: 'mvvm-solid-principle-staging.firebasestorage.app',
    measurementId: 'G-GKXX4B96V2',
  );
}
