// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMZWAaES2WAyEehkhjhS6A4kMdmIBfJKA',
    appId: '1:537539882873:web:18fafd842b4586aaaec9a8',
    messagingSenderId: '537539882873',
    projectId: 'penh-delivery-staging',
    authDomain: 'penh-delivery-staging.firebaseapp.com',
    storageBucket: 'penh-delivery-staging.firebasestorage.app',
    measurementId: 'G-98XT36JJ7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZGJH7XpJBdFWHFflfM2bTa6zGbja_6SY',
    appId: '1:537539882873:android:e74ecc89829512a7aec9a8',
    messagingSenderId: '537539882873',
    projectId: 'penh-delivery-staging',
    storageBucket: 'penh-delivery-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3v25G1FnKq4avTcGLjaOc5nW0QwC1OQ',
    appId: '1:537539882873:ios:922c35d2f9a1a01baec9a8',
    messagingSenderId: '537539882873',
    projectId: 'penh-delivery-staging',
    storageBucket: 'penh-delivery-staging.firebasestorage.app',
    iosBundleId: 'com.penh.delivery.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3v25G1FnKq4avTcGLjaOc5nW0QwC1OQ',
    appId: '1:537539882873:ios:a6d0a382cb213e1eaec9a8',
    messagingSenderId: '537539882873',
    projectId: 'penh-delivery-staging',
    storageBucket: 'penh-delivery-staging.firebasestorage.app',
    iosBundleId: 'com.example.todoKh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMZWAaES2WAyEehkhjhS6A4kMdmIBfJKA',
    appId: '1:537539882873:web:6163b1bc2055c7d2aec9a8',
    messagingSenderId: '537539882873',
    projectId: 'penh-delivery-staging',
    authDomain: 'penh-delivery-staging.firebaseapp.com',
    storageBucket: 'penh-delivery-staging.firebasestorage.app',
    measurementId: 'G-DB84R3ZKQK',
  );

}